:leveloffset: +1

:nixbook_name: Nixbook

include::intro.adoc[]

**However, you cannot install applications in the same way you can on Windows.**

Nixbooks come pre-loaded with Google Chrome, Zoom, Libreoffice and a handful of other basic apps.
This is all 99% of users need.
And it also comes with a software store that is loaded with great free software.

include::default-user.adoc[]

include::updates.adoc[]

= Here is how to use the basics of your new computer

On the bottom right, you'll see the time, battery and where you will connect to the Internet.

Pressing the windows button, or clicking the Start logo in the bottom left, will open up your "start menu" where you can find all your programs, install new ones, change settings, shutdown and restart.

To add new software (apps), click on the icon with the blue circle with the white dots.
From there you can search for and install almost anything you'll need. And these are all completely free to install and use.
(if you don’t see your apps after you install, just reboot and they should be in your menu)

Clicking in the gray icon with the switches will get you into settings. You can customize your system exactly how you want.
To change the default user and/or password, click on Users and Groups.

Also in settings, if the fonts are too small (or big), click on Font Selection and change the text scaling.

== What about Microsoft office?

Your computer is already loaded with Libreoffice, which is a free alternative to MS Office and fully compatible.
However, if you need to use the official MS Office for some reason. Simply use office 365 in your chrome browser.

== What about games?

Your computer might already have some games installed, but you can also search the software center for more.
Also in the software center, you can install Steam, and install pretty much any game you like (if your computer can run it)

Once you are logged into Steam, click Steam / Settings, and click on Compatibility. "Toggle Enable Steam Play for all over titles".

== What about other programs?

If you do have a windows only program that you need to run, you can search for and install "Bottles" from the software center, which should allow you to install your windows only program.

include::end.adoc[]
